# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: menu_development
  username: andrii
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: menu_test
  username: andrii
  password: admin
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: menu_production
  username: andrii
  password: admin
  host: localhost